VacationManagerApp/VacationManagerApp.Web/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using VacationManagerApp.Data;
using VacationManagerApp.Services;
using VacationManagerApp.Services.Contracts;
using VacationManagerApp.ViewModels.Projects;
using VacationManagerApp.ViewModels.Users;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace VacationManagerApp.Web.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly IProjectService projectService;

        public ProjectsController(ApplicationDbContext context, IProjectService projectService)
        {
            context = context;
            this.projectService = projectService;
        }
        public async Task<IActionResult> Index(IndexProjectsViewModel model)
        {
            model = await projectService.GetProjectsAsync(model);
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateProjectViewModel model)
        {
            if (ModelState.IsValid)
            {
                await projectService.CreateProjectAsync(model);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await projectService.GetProjectDetails(id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }
        [HttpGet]
        public async Task<IActionResult> RemoveTeamFromProject(string id)
        {
            var model = await projectService.GetTeamToRemoveAsync(id);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> RemoveTeamFromProject(RemoveTeamViewModel model)
        {
            if (ModelState.IsValid)
            {
                await projectService.RemoveTeamFromProject(model);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> AddTeamToProject(string id)
        {
            var model = await projectService.GetTeamToAddAsync(id);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddTeamToProject(AddTeamToProject model)
        {
            if (ModelState.IsValid)
            {
                await projectService.AddTeamToProject(model);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var model = await projectService.GetProjectToEditAsync(id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditProjectViewModel model)
        {
            if (ModelState.IsValid)
            {
                await projectService.UpdateProjectAsync(model);
                return this.RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await projectService.DeleteProjectAsync(id);


            return RedirectToAction(nameof(Index));
        }
    }
}

VacationManagerApp/VacationManagerApp.Web/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using VacationManagerApp.Data;
using VacationManagerApp.Data.Models;
using VacationManagerApp.ViewModels;
using VacationManagerApp.Data;
using VacationManagerApp.ViewModels.Roles;
using VacationManagerApp.Common;

namespace VacationManager.Controllers
{
    public class RolesController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ApplicationDbContext _db;
        private readonly RoleManager<IdentityRole> _roleManager;
        public RolesController(ApplicationDbContext db, UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _db = db;
            _roleManager = roleManager;
        }
        [Authorize(Roles = GlobalConstants.AdminRole)]
        public async Task<IActionResult> Index()
        {
            List<IdentityRole> roles = _roleManager.Roles.ToList();
            Dictionary<string, int> rolesMembersCount = new Dictionary<string, int>();
            foreach (var role in roles)
            {
                var usersInRole = await _userManager.GetUsersInRoleAsync(role.Name);
                rolesMembersCount.Add(role.Name, usersInRole.Count);
            }
            return View(rolesMembersCount);
        }
        public async Task<IActionResult> Members(string id)
        {
            if (await _roleManager.RoleExistsAsync(id))
            {
                RolesMembersViewModel data = new RolesMembersViewModel();
                data.Members = new List<User>(await _userManager.GetUsersInRoleAsync(id));
                data.RoleName = id;
                return View(data);
            }
            return NotFound();
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (!await _roleManager.RoleExistsAsync(id))
            {
                return NotFound();
            }

            RolesEditViewModel data = new RolesEditViewModel();
            IdentityRole role = await _roleManager.FindByNameAsync(id);
            data.RoleName = role.Name;
            data.RoleId = role.Id;

            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeRoleName(RolesEditViewModel data)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(data.RoleId);

            if (role == null)
            {
                return NotFound();
            }

            role.Name = data.RoleName;
            role.NormalizedName = data.RoleName.ToUpper();

            await _db.SaveChangesAsync();

            return RedirectToAction("Members", new { id = data.RoleName });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string roleName)
        {
            if (!await _roleManager.RoleExistsAsync(roleName))
            {
                return NotFound();
            }

            IdentityRole roleToDelete = await _roleManager.FindByNameAsync(roleName);

            await _roleManager.DeleteAsync(roleToDelete);

            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel data)
        {
            await _roleManager.CreateAsync(new IdentityRole(data.NewRoleName));
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

VacationManagerApp/VacationManagerApp.Web/Controllers/TeamsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using VacationManagerApp.Data;
using VacationManagerApp.Services.Contracts;
using VacationManagerApp.ViewModels.Teams;

namespace VacationManagerApp.Web.Controllers
{
    public class TeamsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ITeamService teamService;

        public TeamsController(ApplicationDbContext context, ITeamService teamService)
        {
            _context = context;
            this.teamService = teamService;
        }
        [Authorize]
        public async Task<IActionResult> Index(IndexTeamsViewModel model)
        {
            model.LogedUserid = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            model = await teamService.GetTeamsAsync(model);
            return View(model);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await teamService.GetTeamDetails(id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateTeamViewModel model)
        {
            if (ModelState.IsValid)
            {
                await teamService.CreateTeamAsync(model);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await teamService.GetTeamToEditAsync(id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditTeamViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await teamService.EditTeamAsync(model);

                if (result == false)
                {
                    return NotFound();
                }

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurant = await teamService.GetTeamDetails(id);
            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }

        // POST: Restaurants/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await teamService.DeleteTeamAsync(id);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> AddUserToTeam(string id)
        {
            var model = await teamService.GetUserToAddAsync(id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddUserToTeam(AddUserToTeamViewModel model)
        {
            if (ModelState.IsValid)
            {
                await teamService.AddUserToTeamAsync(model);
                return this.RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        public async Task<IActionResult> AssignLeader(string id)
        {
            var model = await teamService.GetUserToAssignAsync(id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AssignLeader(AddUserToTeamViewModel model)
        {
            if (ModelState.IsValid)
            {
                await teamService.AssignUserToTeamAsync(model);
                return this.RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        public async Task<IActionResult> RemoveUserOfTeam(string id)
        {
            var model = await teamService.GetUserToRemoveAsync(id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveUserOfTeam(AddUserToTeamViewModel model)
        {
            if (ModelState.IsValid)
            {
                await teamService.RemoveUserOfTeamAsync(model);
                return this.RedirectToAction(nameof(Index));
            }
            return View(model);
        }
    }
}

VacationManagerApp/VacationManagerApp.Web/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using VacationManagerApp.Common;
using VacationManagerApp.Services.Contracts;
using VacationManagerApp.Services;
using System.Security.Claims;
using VacationManagerApp.ViewModels.Users;

namespace VacationManager.Web.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserService service;

        public UsersController(IUserService service)
        {
            this.service = service;
        }
        [Authorize(Roles = GlobalConstants.AdminRole)]
        public async Task<IActionResult> Index(IndexUsersViewModel? model)
        {

            model = await service.GetUsersAsync(model);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                await service.CreateUserAsync(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var model = await service.GetUserToEditAsync(id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                await service.UpdateUserAsync(model);
                return this.RedirectToAction(nameof(Index));
            }
            return View(model);
        }
		[HttpGet]
		public async Task<IActionResult> AddToTeam(string id)
		{
			var model = await service.GetUserToAddAsync(id);
			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> AddToTeam(AddToTeamViewModel model)
		{
			if (ModelState.IsValid)
			{
				await service.AddUserToTeamAsync(model);
				return this.RedirectToAction(nameof(Index));
			}
			return View(model);
		}

		[HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            var userViewModel = await service.GetUserDetailsAsync(id);
            if (userViewModel == null)
            {
                return NotFound();
            }

            return View(userViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Seed()
        {
            const string Password = "123456";
            for (int i = 0; i < 20; i++)
            {
                string result = await service.CreateUserAsync(

                      new CreateUserViewModel()
                      {
                          FirstName = $"Name {i}",
                          LastName = $"LastName {i}",
                          Password = Password,
                          ConfirmPassword = Password,
                          Email = $"user{i}@app.bg",
                          Role = GlobalConstants.Unassigned
                      }
                      );
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            if (id != userId)
            {
                await service.DeleteUserAsync(id);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            string returnUrl = Url.Content("~/");


            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await service.Login(model);
                if (result.Succeeded)
                {
                    // _logger.LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    // _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return View(model);
                }
            }

            // If we got this far, something failed, redisplay form
            return RedirectToAction(nameof(Index), "Home");
        }
    }
}

VacationManagerApp/VacationManagerApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - VacationManagerApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VacationManagerApp.Web.styles.css" asp-append-version="true" />
    <style>
        body {
            font-size: 20px;
            font-weight: 600;
            margin: 0;
            padding: 0;
            font-family: Garamond, serif;
            background-image: url('https://img.freepik.com/premium-photo/laptop-computer-blank-paper-card-sheet-glasses-fan-leaf-golden-accessories-white-background-minimalist-aesthetic-workspace-business-concept-copy-space_408798-11675.jpg');
            background-size: cover;
            background-position: center;
            color: #000000;
            text-align: center;
        }

        h1 {
            font-size: 4rem; 
            margin-top: 40vh; 
            letter-spacing: 2px;
            text-transform: uppercase;
            font-weight: bold;
            background: linear-gradient(to right, #ffec61, #f321d7, #17ead9);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            color: blue; 
            animation: glitter 3s infinite linear alternate;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VacationManagerApp.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="Index">Teams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Requests" asp-action="Index">My Requests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Index">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Requests" asp-action="Pending">Pending</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <p></p>
    <p></p>
    <p></p>
    <p></p>

    <footer class="border-top footer text-muted">
        <div>
            <p></p>
            <p></p>
        </div>
        <div class="container">
            &copy; 2024 - VacationManagerApp.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
``

VacationManagerApp/VacationManagerApp.Web/Views/Shared/_PagingPartial.cshtml
@model PagingViewModel


<nav aria-label="..." class="">
    <ul class="pagination  justify-content-center ">
        <li style="margin-right:5px">
            <form asp-action="@Model.Action" method="post" id="pageSizeForm">

                <select asp-for="ItemsPerPage" class="form-control border-dark" onchange="changeItemsPerPage();">
                    <option value="5">5</option>
                    <option value="10">10</option>
                    <option value="25">25</option>
                    <option value="50">50</option>
                </select>

                <input type="submit" id="loginSubmit" style="visibility:hidden" />
            </form>
        </li>
        <li class="page-item @if (!Model.HasPreviousPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="@Model.Action" asp-route-page="@Model.PreviousPageNumber" asp-route-itemsPerPage="@Model.ItemsPerPage">Back
                <i class="fas fa-step-backward"></i>
            </a>
        </li>
        @for (int i = Model.Page - 2; i < Model.Page; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="@Model.Action" asp-route-page="@i" asp-route-itemsPerPage="@Model.ItemsPerPage">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.Page
                <span class="sr-only"></span>
            </span>
        </li>
        @for (int i = Model.Page + 1; i <= Model.Page + 2; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="@Model.Action" asp-route-page="@i" asp-route-itemsPerPage="@Model.ItemsPerPage">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="@Model.Action" asp-route-page="@Model.NextPageNumber" asp-route-itemsPerPage="@Model.ItemsPerPage"><i class="fas fa-step-forward">Next</i></a>
        </li>
    </ul>
</nav>

<script type="text/javascript">
    
    function changeItemsPerPage() {
       
        document.getElementById('pageSizeForm').submit();
    }
</script>